### ISSUE TITLE
setting up the package

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/soilpalettes#1]
when I do
`library(roxygen2); 
devtools::document()`  

I get this error:  

> Updating soilpalettes documentation
First time using roxygen2. Upgrading automatically...
Loading soilpalettes
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :

I was previously able to run this and create a file for `man` directory. But I f-d something up, and can't do it now.

**Comment by bpbond** [comment]
Hmm. Let me clone and take a look.

**Comment by bpbond** [comment]
Congratulations that was a pretty screwed-up package! 👏 😉 

See PR #2

**Comment by bpbond** [comment]
P.S. Sorry for the snark. They're beautiful palettes!

**Comment by kaizadp** [comment]
> Congratulations that was a pretty screwed-up package!

a new personal record!  

No need to apologize. Love the snark.
Thanks for your help!

**Comment by kaizadp** [comment]
I understood most of what you did. It would be useful to discuss the details, for this, and for future work.
